#+TITLE: Things that need explanation

* Intro
So it's no secret that I'm not particularly knowledgeable when it comes to languages and compilers,
and this compiler is the largest and most complicated piece of software I've ever tried writing.
With the language design and compiler code base being as volatile as they are,
my ability to write clean code is put to the test.
Here I'll note the parts of the code base in particular need of explanation.
If you want to understand anything at all, I recommend you start at the main method.
* The Codebase
** Identifiers
The _ identifier is turned into an identifier with length 0 by the lexer.
This can be problematic as by no means all identifiers can be underscores.
In the future I might make some system where identifiers get assigned numbers from the lexer,
but then you would need a bidirectional map for printing proper error messages.
See github issue #4 to see if I ever did do this
** Namespaces, Namedefs and NameScopes
A Namespace is anything that contains named definitions, so both a NameScopeExpression (global, unordered), and a normal Scope (ordered definitions and statements) count.
Namedefs are definitions to NameScopeExpressions, a NameScope being one of such, import declarations being another option.
The namedef assigns a name to the NameScopeExpression, allowing you to put them withing each other and reference one another.
The NamespaceStack is used when resolving references in the language. It is pushed and popped when entering NameScopes and normal Scopes,
with the difference being not all identifiers in the Scope being added at once, but rather as you go.
** Concretable
*** TODO Write this
** The =try= prefix in function names
It means we won't print an error message upon a failed attempt at doing whatever it is the function tries to do. Instead you'll get a null pointer or something similar
Note that this rule isn't always followed
* Optimizations
** Strings as integers
In the future we should definitely turn identifiers to indecies in a map, saving strings from moving about.
Github issue #4
** Binary search for tokens
We don't want to compare every word with all reserved words.
Github issue #7
** The Concretable stuff
It's n log n, which is good without having a vector in every single Concretable
Doing it that way would be O(n) I think, but the memory fragmentation with the default allocation would be horrid
* The Language
** Implicit evaluation
A def consists of a name and a FunctionExpression. When just referencing the def by name, the function is implicitly called.
When a def has parameters, it can't be implicitly called, as you must supply the parameters.
The function call operator tells its operand that it shouldn't implicitly evaluate any functions, this is then relayed down though expressions
The type of the expression can then become a FunctionType, and when you codegen the expression, the function is not called, but returned as a Value*.
Now what's interesting is that if the returned FunctionType* is unique to a FunctionExpression, we don't need to do any function pointer calls.

#+BEGIN_SRC daf
def func(a:i32) := 6+a;
def otherFunc := func;

def use {
    print(otherFunc(4));
};
#+END_SRC

otherFunc has the signature ():(a:i32):i32, but the actual LLVM signature is just (), as the returned value has the type FunctionType, with a specific FunctionExpression

