#+TITLE: Things that need explanation

* Intro
So it's no secret that I'm not particularly knowledgeable when it comes to languages and compilers,
and this compiler is the largest and most complicated piece of software I've ever tried writing.
With the language design and compiler code base being as volatile as they are,
my ability to write clean code is put to the test.
Here I'll note the parts of the code base in particular need of explanation.
If you want to understand anything at all, I recommend you start at 
* The Codebase
** Expressions
*** evaluatesToValue() and needsSemicolonAfterStatement()
These two boolean-returning methods in Expression are used by the statement parser.
Expressions can be statements if =isStatement()= returns true.
Normally statements are followed by semicolons, but statements like if, for, while etc. don't need them.
These special statements actually contain another statement, which often is a scope.
A scope is an expression, defined in Scope.hpp, and it overrides the two methods we started with.
Scopes can evaluate to the last expression, and is thus itself an expression, but it may also not.
In which case, it would be bad if the enclosing scope thought it returned something.
Therefore, a Scope may only have a final out expression that has evaluatesToValue() return true.
In which case the scope itself will do the same, allowing you to chain final out expressions.

needsSemicolonAfterStatement() is also used by the statement parser.
A scope normally doesn't need a trailing semicolon, but if it evaluates to a value,
it behaving like a statement which doesn't becomes weird. To avoid fooling yourself,
a scope returning a value gets the same treatment as any other expression.
Note: This function is by no means pure. It will log a warning if it returns true from a Scope.
That warning will explain why you need a semicolon after the scope, but will be emitted every time.

As a final note and TODO for myself: Do I need two methods? ...or would just one suffice, as they both:
 - return true by default
 - return false for normal scopes
 - return true for scopes that return something

* The Language
