#ifndef TOKEN_PRIMITVE_BIND
#  error Please define TOKEN_PRIMITVE_BIND before including TokenPrimitveMapping.hpp
#endif

TOKEN_PRIMITVE_BIND(U8_TOKEN, U8)
TOKEN_PRIMITVE_BIND(I8_TOKEN, I8)
TOKEN_PRIMITVE_BIND(U16_TOKEN, U16)
TOKEN_PRIMITVE_BIND(I16_TOKEN, I16)
TOKEN_PRIMITVE_BIND(U32_TOKEN, U32)
TOKEN_PRIMITVE_BIND(I32_TOKEN, I32)
TOKEN_PRIMITVE_BIND(U64_TOKEN, U64)
TOKEN_PRIMITVE_BIND(I64_TOKEN, I64)
TOKEN_PRIMITVE_BIND(BOOLEAN, BOOL)
TOKEN_PRIMITVE_BIND(USIZE, USIZE)
TOKEN_PRIMITVE_BIND(ISIZE, ISIZE)
TOKEN_PRIMITVE_BIND(CHAR, CHAR)
