type token =
  | PUB | LET | DEF | WITH | AS | MUT | UNCRT | MOVE | COPY
  | CLASS | TRAIT | ENUM | PROT
  | CTOR | DTOR | THIS | THIS_TYPE
  | VIRT | OVERRIDE

  | IF | ELSE | FOR | WHILE | DO | MATCH
  | CONTINUE | BREAK | RETRY | RETURN

  | CHAR
  | I8 | U8 | I16 | U16 | I32 | U32 | I64 | U64
  | USIZE | ISIZE | BOOL | F32 | F64

  | SIZEOF | TYPEOF | LENGTHOF
  | TRUE | FALSE | NULL

  | ASSIGN | TYPE_SEPARATOR | STATEMENT_END | LEFT_PAREN | COMMA | RIGHT_PAREN
  | SCOPE_START | SCOPE_END | CLASS_ACCESS | DEREFERENCE
  | LEFT_BRACKET | RIGHT_BRACKET | TYPE_INFERED

  | PLUS | MINUS | MULT | DIVIDE | MODULO
  | REF | BITWISE_OR | BITWISE_XOR | NOT | BITWISE_NOT
  | LOWER | GREATER | Q_MARK

  | DECLARE | MODULE_ACCESS
  | LSL | ARS | LSR | LOGICAL_AND | LOGICAL_OR
  | EQUALS | NOT_EQUALS | GREATER_OR_EQUAL | LOWER_OR_EQUAL | PLUS_PLUS | MINUS_MINUS

  | MUT_REF

  | IDENTIFIER of string | STRING_LITERAL of string | INTEGER_LITERAL of int | REAL_LITERAL of float
  | END_TOKEN | ERROR_TOKEN of char
