* My OCaml Adventure
Before you design a programming language you should probably know several languages following different paradigms.
I'd never tried functional programming before, and seeing as the LLVM tutorial was avaliable in it,
OCaml seemed like a great place to start.

** The packages I installed
Keep in mind you don't need all these to build the compiler
*** Pacman on Manjaro (Arch Linux)
- ocaml
- llvm-ocaml
- opam
- ocaml-compiler-libs
- ocaml-findlib
*** Opam
=opam init=
=eval `opam config env`=
Add to .bashrc: =. /home/haavard/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true=
=opam switch 4.06.1= NB!: Takes forever
*** Build system
=opam install oasis=

*** Emacs mode
=opam install ocp-indent=
=opam install merlin=
Restart emacs server

* My setup
I'm sort of guessing this only has to be done once, but I'd like to save the instructions.
=oasis setup -setup-update dynamic=
This generates =setup.ml=, =Makefile= and the =configure= script, which should be checked into git

* Redoing oasis
I'm not sure changes to the =_oasis= file are automatically read, so I might want to re-run the oasis generation.
=rm setup.ml Makefile configure=
Then follow the /My setup/ section

* Resources used:
Learned oasis from here: https://ocaml.org/learn/tutorials/get_up_and_running.html
