* Getting things to build
Before you design a programming language you should probably know several languages following different paradigms.
I'd never tried functional programming before, and seeing as the LLVM tutorial was avaliable in it,
OCaml seemed like a great place to start.

** The packages I installed
*** Pacman on Manjaro (Arch Linux)
- opam
**** Probably don't have these installed using pacman, see opam
- ocaml
- llvm-ocaml
- ocaml-compiler-libs
- ocaml-findlib
*** Initializing opam
=opam init=
=eval `opam config env`=
Add to .bashrc: =. /home/haavard/.opam/opam-init/init.sh > /dev/null 2> /dev/null || true=
=opam switch 4.06.1= This is the OCaml compiler I use. NB!: Switching takes forever
*** Build system packages
**** TODO: Find out
I'm not sure if the oasis package is needed to use the oasis generated Makefile (checked into git)
=opam install oasis=
=opam install core=
*** Dependencies
Many of these packages also exist in pacman, but if you use opam you'll be sure to get the correct package version for your compiler
I don't know if oasis automatically installs dependencies or not
=opam install llvm.6.0.0 camlp4 compiler-libs findlib=

*** Emacs mode
I use spacemacs with the ocaml layer
=opam install ocp-indent=
=opam install merlin=
Restart emacs server

* My oasis setup
Source: https://ocaml.org/learn/tutorials/setting_up_with_oasis.html
I'm sort of guessing this only has to be done once, but I'd like to save the instructions.
=oasis setup -setup-update dynamic=
This generates =setup.ml=, =Makefile= and the =configure= script, which should be checked into git

* Clean build (even cleaner than git clean)
** There is no 'make clean'
Removing files made by 'make', which should all be .gitignored
=cd <repo/OCompiler>=
=rm _build -r=
=rm dafc_main.native setup.data setup.log=
** Removing files generated by oasis
These files are already checked into git, and changes to the =_oasis= file seem to be read whenever you run make.
In case you do want to force a complete rerun:
=cd <repo/OCompiler>=
=rm setup.ml Makefile configure=
To re-generate the files, see: My oasis setup

* Resources used:
Learned oasis from here: https://ocaml.org/learn/tutorials/get_up_and_running.html
